### ISSUE TITLE
One TCGA sample possibly be used twice in figure 7.

### ISSUE THREAD

**Issue by YukuanHuang** [effiken/Leader_et_al#1]
Hi,

Appreciations for your wonderful job!

When I was trying to repeat Figure 7, I noticed there is a duplicate column in generated expr_mat matrix. I'm not sure but maybe the lines 102 and 103 were ordered incorrectly so the first sample had been removed from the combined matrix.
` uuids <- uuids[-1]
  fn <- uuids[1]`

**Comment by leaderam** [comment]
Thank you for your email bringing this to our attention! I will look into
this and get back to you as soon as possible.
Best,
Andrew

**Comment by YukuanHuang** [comment]
I rechecked the code and found that the duplicate column names are from different files/UUID's corresponding to the same matched short TCGA barcode and all of them are picked for analysis.
