### ISSUE TITLE
Where to find treatment outcome?

### ISSUE THREAD

**Issue by ZhenjiangFan** [effiken/Leader_et_al#3]
Hi,

Thank you for your fantastic work.

I noticed that the column "treatment_outcome" in the "TCGA-LUAD_clinical.csv" file under the folder "input_tables" has no actual values. I have been trying to find a variable representing "responder and non-responder" information about a therapeutic treatment but have had any luck so far. I wonder if you would have any idea where to get such information?

Thank you.

Fan

**Comment by effiken** [comment]
Hi Fan, thank you for your interest in the study. We did not have response data for TCGA. Data on POPLAR study was published in another study: https://doi.org/10.1016/j.ccell.2022.02.002.

**Comment by ZhenjiangFan** [comment]
Thank you for your response.

Fan
